/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dannyleavitt' at '10/31/16 6:13 PM' with Gradle 2.12
 *
 * @author dannyleavitt, @date 10/31/16 6:13 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
